Repository FRONTENDSCHOOLPLUS2/trifly, pull requests merged in 2024-09, with the labels that each got.

#296 🔀 merge: from feature/seatmapscroll to dev
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/app/(primary)/order/seat-map/[id]/seatmapGrid.scss
  src/components/Scroll/Scroll.scss
  src/components/Scroll/Scroll.tsx
Labels: 리팩토링

#299 🔀 merge: from feature/filter to dev
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/types/code.ts
Labels: 리팩토링

#300 🔀 merge: from feature/scroll to dev
  src/app/(primary)/order/seat-map/[id]/seatmapGrid.scss
  src/components/Scroll/Scroll.scss
Labels: 리팩토링

#302 🔀 merge: from feature/snsLogin to dev
  auth.d.ts
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/login.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/atoms/atoms.ts
  src/auth.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/Logout.tsx
  src/data/actions/authAction.ts
  src/types/user.ts
Labels: 개발

#303 🔀 merge: from feature/recentSearch to dev
  src/atoms/atoms.ts
  src/components/RecentSearch/RecentSearch.tsx
  src/components/RecentSearch/RecentSearchResult.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#305 🔀 merge: from optimization/cls to dev
  src/app/(default)/layout.tsx
  src/app/(primary)/layout.tsx
  src/app/(transparent)/footprint/footprint.scss
  src/app/(transparent)/layout.tsx
  src/app/layout.tsx
Labels: 리팩토링

#307 🔀 merge: from feature/snsLoginBug to dev
  src/auth.ts
  src/components/layout/Header/Logout.tsx
Labels: 버그 수정

#308 🔀 merge: from feature/recentSearch to dev
  src/components/RecentSearch/RecentSearchResult.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#310 🔀 merge: from feature/saveFileters to dev
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/result.scss
Labels: 리팩토링

#312 🔀 merge: from feature/footerEdit to dev
  src/components/layout/Footer/Footer.scss
  src/components/layout/Footer/Footer.tsx
Labels: 리팩토링

#313 🔀 merge: from feature/reservationList to dev
  src/app/(primary)/reservation/OrdersItem.tsx
Labels: 리팩토링

#314 🔀 merge: from feature/reservationDetailDate to dev
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/[reservationDetail]/Journey.tsx
Labels: 리팩토링

#315 🔀 merge: from feature/testOrderSkip to dev
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/middleware.ts
Labels: 리팩토링

#316 🔀 merge: from feature/saveFilters to dev
  src/FilterStateManager.tsx
  src/RecoilWrapper.tsx
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/layout.tsx
  src/atoms/atoms.ts
  src/hook/useAllChecked.ts
Labels: 리팩토링

#317 🔀 merge: from feature/reservationPagination to dev
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/Pagination.tsx
  src/app/(primary)/reservation/ReservationList.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/(primary)/reservation/reservaionList.scss
Labels: 리팩토링

#318 🔀 merge: from feature/order to dev
  public/img/icon-warning-primary.svg
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/agree/AgreeForm.tsx
  src/app/(primary)/order/order.scss
  src/components/Accordion/AccordionBody.tsx
  src/components/Accordion/accordion.scss
  src/styles/responsive.scss
Labels: 개발

#320 🔀 merge: from feature/pagination to dev
  src/app/(primary)/reservation/Pagination.tsx
  src/app/(primary)/reservation/ReservationList.tsx
  src/app/(primary)/reservation/[reservationDetail]/page.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/(primary)/reservation/pagination.scss
  src/components/Pagination/Pagination.scss
  src/components/Pagination/Pagination.tsx
  src/lib/fetchOrder.tsx
Labels: 리팩토링

#326 🔀 merge: from feature/csrfBug to dev
  .gitignore
  api/dbinit/getDB.js
  api/dbinit/init.js
  api/dbinit/package-lock.json
  api/dbinit/package.json
  api/dbinit/team/data.js
  auth.d.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/auth.ts
  src/components/layout/Header/Logout.tsx
  src/data/actions/authAction.ts
  src/data/actions/signoutAction.ts
Labels: QA

#329 🔀 merge: from eslint/heesun to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/app/(primary)/reservation/Pagination.tsx
  src/app/(primary)/reservation/ReservationList.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/e-ticket/[ticketId]/[passengerId]/page.tsx
  src/lib/fetchOrder.tsx
Labels: 버그 수정

#331 🔖 release: ver 1.1.3
  src/app/(transparent)/footprint/[orderId]/[passengerId]/page.tsx
Labels: 개발

#333 🔀 merge: from feature/footprint to dev
  public/img/img-footprint-bg1.jpg
  public/img/img-footprint-bg1.webp
  public/img/img-footprint-bg2.jpg
  public/img/img-footprint-bg2.webp
  public/img/img-map.png
  src/app/(transparent)/footprint/Animation.tsx
  src/app/(transparent)/footprint/footprint.scss
  src/components/Ticket/Canvas.tsx
  src/components/Ticket/Ticket.tsx
  src/components/Ticket/ticket.scss
  src/styles/common.scss
Labels: 리팩토링, QA

#337 🔀 merge: from feature/pagination to dev
  src/app/(primary)/reservation/ReservationList.tsx
Labels: 리팩토링

#338 🔀 merge: from feature/reservationStyle to dev
  src/app/(primary)/reservation/OrdersItem.scss
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/Pagination.tsx
  src/app/(primary)/reservation/ReservationList.tsx
  src/app/(primary)/reservation/Search.scss
  src/app/(primary)/reservation/Search.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/(primary)/reservation/pagination.scss
  src/app/(primary)/reservation/reservation.scss
Labels: 리팩토링, 디자인

#340 🔀 merge: from feature/orderQA to dev
  src/app/(primary)/order/layout.tsx
  src/app/layout.tsx
  src/components/Accordion/accordion.scss
Labels: QA

#341 🔀 merge: from feature/filterSave to dev
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
Labels: 리팩토링

#344 🔀 merge: from feature/orderQA to dev
  src/app/(primary)/order/payment/PaymentForm.tsx
Labels: QA

#345 🔀 merge: from feature/ListInfiniteScroll to dev
  package-lock.json
  package.json
  src/RecoilWrapper.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(primary)/reservation/OrdersItem.tsx
Labels: 리팩토링

#348 🔀 merge: from refactor/filter to dev
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/Sorting.tsx
  src/components/Filters/AirlineFilter.tsx
  src/components/Filters/NonstopFilter.tsx
  src/components/Filters/OriginArrTime.tsx
  src/components/Filters/OriginDepTime.tsx
  src/components/Filters/PriceFilter.tsx
  src/components/Filters/ReturnArrTime.tsx
  src/components/Filters/ReturnDepTime.tsx
Labels: 리팩토링

#350 🔀 merge: from feature/ListInfiniteScroll to dev
  src/app/(primary)/reservation/MobileReservationList.tsx
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/OrdersList.tsx
  src/app/(primary)/reservation/ReservationList.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/api/orders/route.ts
  src/lib/FetchOrderListScroll.tsx
  src/lib/RQProvider.tsx
Labels: 개발, 리팩토링

#351 🔀 merge: from feature/ListInfiniteScroll to dev
  package-lock.json
  package.json
Labels: 리팩토링

#352 🔀 merge: from feature/infiniteScrollStylw to dev
  src/app/(primary)/reservation/(infiniteScroll)/MobileReservationList.tsx
  src/app/(primary)/reservation/(infiniteScroll)/OrderList.scss
  src/app/(primary)/reservation/(infiniteScroll)/OrdersList.tsx
  src/app/(primary)/reservation/OrdersList.tsx
  src/app/(primary)/reservation/page.tsx
Labels: 리팩토링, 디자인

#353 🔀 merge: from feature/reservation to dev
  src/app/(primary)/reservation/page.tsx
Labels: 리팩토링
