Repository FRONTENDSCHOOLPLUS2/trifly, pull requests merged in 2024-12, with the labels that each got.

#358 🔀 merge: from feature/ticket to dev
  src/components/Accordion/accordion.scss
  src/components/Ticket/Canvas.tsx
  src/components/Ticket/ticket.scss
Labels: 리팩토링

#361 🔖 release: ver 1.1.5
  src/app/api/orders/route.ts
Labels: 개발

#363 메인화면 기능 수정
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/page.tsx
  src/components/Filters/AirlineFilter.tsx
  src/components/Filters/NonstopFilter.tsx
  src/components/Filters/OriginArrTime.tsx
  src/components/Filters/OriginDepTime.tsx
  src/components/Filters/PriceFilter.tsx
  src/components/Filters/ReturnArrTime.tsx
  src/components/Filters/ReturnDepTime.tsx
  src/components/RecentSearch/RecentSearch.scss
  src/components/TicketSearch/SearchModals/ItineraryModal.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
Labels: 리팩토링

#365 항공권 필터 리팩토링 완료
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Sorting.tsx
  src/components/Filters/AirlineFilter.tsx
  src/hook/useFilters.ts
Labels: 리팩토링

#369 Hotfix: 초기 데이터 로드 문제 해결 후 배포 중
  src/app/(default)/(ticket)/ticket-result/Result.tsx
Labels: SOS 구조요청

#371 Hotfix: 항공사 필터 문제 해결 중
  src/app/(default)/(ticket)/ticket-result/Result.tsx
Labels: SOS 구조요청

#372 Refactor: 최근 로그인 얼럿 위치 변경, 선택하지 않은 입국편 좌석 변경, 예약자 랜덤 데이터 채우기 기능 구현
  src/app/(default)/(user)/login/login.scss
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/components/Ticket/Ticket.tsx
  src/hook/useCreateTestUser.ts
Labels: 개발, 리팩토링

#374 Hotfix: session 타입 오류 개선
  src/app/(primary)/order/payment/PaymentForm.tsx
Labels: 버그 수정

#379 Style: 포토티켓 수정 반응형 디자인 변경
  src/components/Ticket/ticket.scss
Labels: 디자인, QA
