Repository FRONTENDSCHOOLPLUS2/trifly, pull requests merged in 2024-08, with the labels that each got.

#51 🔀 merge: from feature/button to dev
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Submit/Submit.tsx
  src/styles/variables.css
Labels: 개발

#52 🔀 merge: from feature/layoutSetting to dev
  src/app/(default)/layout.tsx
  src/app/(default)/page.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/order/page.tsx
  src/app/(primary)/page.tsx
  src/app/(transparent)/layout.tsx
  src/app/(transparent)/page.tsx
  src/components/layout/Header/Header.scss
  src/components/layout/Header/Header.tsx
  src/styles/common.css
  src/styles/globals.css
Labels: 디자인

#54 🔀 merge: from feature/inputStyle to dev
  public/img/icon-check.svg
  src/app/(primary)/layout.tsx
  src/app/(primary)/order/page.tsx
  src/styles/common.css
  src/styles/globals.css
  src/styles/responsive.css
Labels: 디자인

#58 🔀 merge: from feature/publicUpdate to dev
  public/img/icon-login-black.svg
  public/img/icon-login-white.svg
  public/img/icon-logout-black.svg
  public/img/icon-logout-white.svg
  public/img/logo-default.svg
  public/img/logo-primary.svg
  public/img/logo-text-blue.svg
  public/img/logo-text-default.svg
  public/img/logo-text-gray.svg
  public/img/logo-text-primary.svg
  public/img/logo-transparent.svg
  src/components/Footer/Footer.tsx
  src/components/layout/Header/Header.tsx
Labels: 개발

#59 🔀 merge: from feature/link to dev
  src/components/Anchor/Anchor.scss
  src/components/Anchor/Anchor.tsx
Labels: 개발

#63 🔀 merge: from feature/error to dev
  public/img/error-mobile.svg
  public/img/error-tablet.svg
  public/img/error.svg
  src/app/not-found.tsx
  src/styles/not-found.scss
Labels: 개발

#65 🔀 merge: from feature/headerStyle to dev
  src/components/layout/Header/Header.scss
Labels: 디자인

#68 🔀 merge: from feature/error to dev
  src/styles/not-found.scss
Labels: 개발

#69 🔀 merge: from feature/loginPost to dev
  .env.d.ts
  auth.d.ts
  package-lock.json
  package.json
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/page.tsx
  src/auth.ts
  src/data/actions/authAction.ts
  src/middleware.ts
Labels: 개발

#70 🔀 merge: from feature/modal to dev
  public/img/icon-close-black.svg
  src/RecoilWrapper.tsx
  src/atoms/atoms.ts
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.tsx
Labels: 개발

#71 🔀 merge: from feature/layoutModify to dev
  src/app/(transparent)/footprint/page.tsx
  src/app/[...not_found]/page.tsx
  src/app/layout.tsx
  src/components/layout/Footer/Footer.scss
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/Header.scss
Labels: 개발

#73 🔀 merge: from feature/snsLogin to dev
  public/img/icon-sns-kakao.svg
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/SnsLogin.tsx
  src/app/(default)/(user)/login/login.scss
  src/app/(default)/(user)/login/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/auth.ts
  src/data/actions/authAction.ts
Labels: 개발

#74 🔀 merge: from feature/mainCode to dev
  env.d.ts
  src/app/(default)/layout.tsx
  src/app/layout.tsx
  src/atoms/atoms.ts
  src/data/fetch/fetchCode.ts
  src/types/code.ts
Labels: 개발

#77 ♻️ refactor: fetchCodes 생성 -> 전역 상태에서 관리 불필요
  src/atoms/atoms.ts
Labels: 개발

#79 🔀 merge: from feature/modalScroll to dev
  src/components/Modal/Modal.tsx
Labels: 개발

#80 🔀 merge: from feature/headerUI to dev
  src/components/layout/Header/Header.scss
Labels: 개발

#83 🔀 merge: from feature/modalUI to dev
  src/components/Modal/Modal.scss
Labels: 개발

#85 🔀 merge: from feature/headerLogin to dev
  src/components/layout/Header/Header.tsx
Labels: 개발

#86 🔀 merge: from feature/mainUI to dev
  public/img/icon-arrow.svg
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/app/(primary)/notices/[id]/page.tsx
Labels: 개발

#88 🔀 merge: from feature/mainUI to dev
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/app/(primary)/notice/[id]/page.tsx
  src/app/(primary)/notice/page.tsx
  src/app/(primary)/notices/[id]/page.tsx
  src/components/Banner/Banner.scss
  src/components/Banner/Banner.tsx
Labels: 개발

#89 🔀 merge: from feature/buttonUI to dev
  src/components/Button/Button.scss
Labels: 개발

#90 🔀 merge: from feature/mainUI to dev
  public/img/icon-oneway-gray.svg
  public/img/icon-roundtrip-gray.svg
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/Banner/Banner.scss
  src/components/RecentSearch/RecentSearch.scss
  src/components/RecentSearch/RecentSearch.tsx
Labels: 개발

#91 🔀 merge: from feature/recentSearch to dev
  src/app/(default)/main.scss
  src/components/RecentSearch/RecentSearch.scss
  src/components/RecentSearch/RecentSearch.tsx
  src/components/RecentSearch/RecentSearchResult.scss
  src/components/RecentSearch/RecentSearchResult.tsx
Labels: 개발

#93 🔀 merge: from feature/signupCredentials to dev
  public/img/icon-accordion-blue.svg
  public/img/icon-accordion-primary.svg
  public/img/icon-check-gray.svg
  src/app/(default)/(user)/signup/Agree.tsx
  src/app/(default)/(user)/signup/Complete.tsx
  src/app/(default)/(user)/signup/Join.tsx
  src/app/(default)/(user)/signup/Step.tsx
  src/app/(default)/(user)/signup/page.tsx
  src/app/(default)/(user)/signup/signup.scss
  src/app/(default)/(user)/user.scss
  src/app/layout.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionBody.tsx
  src/components/Accordion/AccordionContext.tsx
  src/components/Accordion/AccordionHeader.tsx
  src/components/Accordion/AccordionItem.tsx
  src/components/Accordion/accordion.scss
  src/components/Progress/Progress.tsx
  src/components/Progress/progress.scss
  src/data/actions/signupAction.ts
  src/styles/common.css
  src/styles/common.scss
  src/styles/globals.scss
  src/styles/responsive.scss
  src/styles/variables.scss
  src/types/user.ts
Labels: 개발

#95 🔀 merge: from feature/fontApply to dev
  src/styles/globals.scss
Labels: 개발

#96 🔀 merge: from feature/modalUI to dev
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.tsx
Labels: 개발

#97 🔀 merge: from feature/mainUI to dev
  src/app/layout.tsx
  src/components/Badge/Badge.scss
Labels: 개발

#98 🔀 merge: from feature/recentSearch to dev
  src/components/RecentSearch/RecentSearch.scss
  src/components/RecentSearch/RecentSearch.tsx
Labels: 개발

#99 🔀 merge: from feature/signupBadge to dev
  src/app/(default)/(user)/signup/Agree.tsx
  src/app/(default)/(user)/signup/signup.scss
Labels: 개발

#103 🔀 merge: from feature/headerUI to dev
  public/img/icon-logout-black.svg
  public/img/icon-logout-white.svg
  src/components/layout/Header/Header.scss
  src/components/layout/Header/Logout.tsx
Labels: 개발

#102 🔀 merge: from feature/testLoginLoad to dev
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/page.tsx
Labels: 개발

#105 🔀 merge: from feature/orderType to dev
  src/types/order.ts
Labels: 개발

#106 🔀 merge: from feature/ticketSearch to dev
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearch.tsx
Labels: 개발

#107 🔀 merge: from feature/headerNav to dev
  src/components/layout/Header/Header.tsx
Labels: 개발

#108 🔀 merge: from feature/reservation to dev
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/[reservationId]/page.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/(primary)/reservation/reservation.scss
  src/components/Pagination/Pagination.scss
  src/components/Pagination/Pagination.tsx
  src/lib/fetchOrder.tsx
  src/styles/globals.scss
Labels: 개발

#112 🔀 merge: from feature/ticketSearch to dev
  public/img/icon-switch.svg
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/Banner/Banner.scss
  src/components/RecentSearch/RecentSearch.tsx
  src/components/TicketSearch/SearchModals/ItineraryModal.scss
  src/components/TicketSearch/SearchModals/ItineraryModal.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearch.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
  src/data/fetch/fetchCode.ts
Labels: 개발

#113 🔀 merge: from feature/routeModal to dev
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#117 🔀 merge: from feature/modal to dev
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.tsx
Labels: 개발

#119 🔀 merge: from feature/modal to dev
  src/components/Modal/Modal.tsx
Labels: 개발

#120 🔀 merge: from feature/passenger modal to dev
  public/img/icon-minus.svg
  public/img/icon-plus.svg
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearch.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#122 🔀 merge: from feature/scheduleSearch to dev
  package-lock.json
  package.json
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#125 🔀 merge: from feature/reservationPrint to dev
  package-lock.json
  package.json
  src/app/e-ticket/[ticketId]/TicketPrint.tsx
  src/app/e-ticket/[ticketId]/page.tsx
  src/types/order.ts
Labels: 개발

#126 🔀 merge: from feature/orderTypeEdit to dev
  src/types/order.ts
Labels: 개발

#128 🔀 merge: from feature/orderPayment to dev
  auth.d.ts
  public/img/icon-warning.svg
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/agree/page.tsx
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/order/payment/page.tsx
  src/auth.ts
  src/hook/usePersonalPrice.ts
  src/styles/globals.scss
  src/types/order.ts
Labels: 개발

#129 🔀 merge: from feature/scheduleSearch to dev
  src/components/TicketSearch/SearchModals/RouteModal.scss
Labels: 개발

#130 🔀 merge: from dev to main
  .gitignore
  auth.d.ts
  env.d.ts
  package-lock.json
  package.json
  public/img/icon-warning.svg
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/agree/page.tsx
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/order/payment/page.tsx
  src/app/e-ticket/[ticketId]/TicketPrint.tsx
  src/app/e-ticket/[ticketId]/page.tsx
  src/auth.ts
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/hook/usePersonalPrice.ts
  src/styles/globals.scss
  src/types/order.ts
Labels: 개발

#134 🔀 merge: from feature/orderLayoutBug to dev
  auth.d.ts
  package-lock.json
  package.json
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/layout.tsx
  src/app/(primary)/order/orderContext.ts
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/types/order.ts
Labels: 개발

#136 🔀 merge: from feature/scheduleSearch to dev
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearchBox.tsx
  src/hook/useCheckWindowWidth.ts
Labels: 개발

#137 🔀 merge: from feature/scheduleModalUI to dev
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
Labels: 개발

#138 🔀 merge: from feature/ticket to dev
  public/img/img-ticket-barcode.svg
  public/img/img-ticket-stamp.svg
  src/components/Ticket/Ticket.tsx
  src/components/Ticket/ticket.scss
  src/data/fetch/fetchCode.ts
  src/types/order.ts
Labels: 개발

#139 🔀 merge: from feature/ticketSearch to dev
  api/dbinit/team/data.js
  src/app/api/ticket/route.ts
Labels: 개발

#140 🔀 merge: from feature/codeTypes to dev
  src/components/TicketSearch/TicketSearch.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
  src/data/fetch/fetchCode.ts
  src/types/code.ts
Labels: 개발

#141 🔀 merge: from feature/orderComplete to dev
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/complete/TicketChk.tsx
  src/app/(primary)/order/complete/page.tsx
  src/app/(primary)/order/order.scss
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Ticket/Ticket.tsx
Labels: 개발

#143 🔀 merge: from feature/allCheck to dev
  src/app/(default)/(user)/signup/Agree.tsx
  src/app/(primary)/order/agree/AgreeForm.tsx
  src/app/(primary)/order/agree/page.tsx
  src/app/(primary)/order/order.scss
  src/hook/useAllChecked.ts
Labels: 개발

#145 🔀 merge: from feature/seat-map to dev
  public/img/exit.svg
  public/img/galley.svg
  public/img/seat-select.svg
  public/img/seat-unselect.svg
  public/img/seat.svg
  public/img/toilet.svg
  public/img/wing.svg
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seat-map.scss
  src/app/(primary)/order/seat-map/test/page.tsx
  src/app/(primary)/order/seat-map/test/seat-map-test.scss
  src/lib/seatMap.tsx
  src/types/flight.ts
Labels: 개발

#146 🔀 merge: from feature/badeUI to dev
  src/components/Badge/Badge.scss
Labels: 개발

#148 🔀 merge: from feature/ticketSearch to dev
  src/app/(default)/(ticket)/ticket-result/TicketResult.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/types/flight.ts
Labels: 개발

#154 🔀 merge: from feature/commonstyle to dev
  src/styles/common.scss
Labels: 디자인

#156 🔀 merge: from eslintFix/JW to dev
  .eslintrc.json
  .prettierrc.cjs
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/app/api/ticket/route.ts
  src/app/not-found.tsx
  src/components/Banner/Banner.tsx
  src/components/TicketSearch/SearchInfo.scss
  src/components/TicketSearch/SearchInfoBox.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearchBox.tsx
  src/components/layout/Header/Header.scss
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/Logout.tsx
  src/hook/useCheckWindowWidth.ts
  tsconfig.json
Labels: 개발

#155 🔀 merge: from eslintFix/SJ to dev
  .eslintrc.json
  next.config.mjs
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/login.scss
  src/app/(default)/(user)/login/page.tsx
  src/app/(default)/(user)/signup/Agree.tsx
  src/app/(default)/(user)/signup/Complete.tsx
  src/app/(default)/(user)/signup/Join.tsx
  src/app/(default)/(user)/signup/Step.tsx
  src/app/(default)/(user)/signup/signup.scss
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/Order.tsx
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/agree/AgreeForm.tsx
  src/app/(primary)/order/complete/TicketChk.tsx
  src/app/(primary)/order/complete/page.tsx
  src/app/(primary)/order/layout.tsx
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/atoms/atoms.ts
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionBody.tsx
  src/components/Accordion/AccordionHeader.tsx
  src/components/Accordion/AccordionItem.tsx
  src/components/Ticket/Ticket.tsx
  src/components/Ticket/ticket.scss
Labels: 개발

#157 🔀 merge: from dev to main
  .eslintrc.json
  .prettierrc.cjs
  next.config.mjs
  package-lock.json
  package.json
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/login.scss
  src/app/(default)/(user)/login/page.tsx
  src/app/(default)/(user)/signup/Agree.tsx
  src/app/(default)/(user)/signup/Complete.tsx
  src/app/(default)/(user)/signup/Join.tsx
  src/app/(default)/(user)/signup/Step.tsx
  src/app/(default)/(user)/signup/signup.scss
  src/app/(default)/main.scss
  src/app/(default)/page.tsx
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/Order.tsx
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/agree/AgreeForm.tsx
  src/app/(primary)/order/complete/TicketChk.tsx
  src/app/(primary)/order/complete/page.tsx
  src/app/(primary)/order/layout.tsx
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/test/page.tsx
  src/app/(primary)/order/seat-map/test/seat-map-test.scss
  src/app/(primary)/reservation/[reservationDetail]/Journey.tsx
  src/app/(primary)/reservation/[reservationDetail]/TicketLink.tsx
  src/app/(primary)/reservation/[reservationDetail]/page.tsx
  src/app/(primary)/reservation/page.tsx
  src/app/api/ticket/route.ts
  src/app/not-found.tsx
  src/atoms/atoms.ts
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionBody.tsx
  src/components/Accordion/AccordionHeader.tsx
  src/components/Accordion/AccordionItem.tsx
  src/components/Banner/Banner.tsx
  src/components/Ticket/Ticket.tsx
  src/components/Ticket/ticket.scss
  src/components/TicketSearch/SearchInfo.scss
  src/components/TicketSearch/SearchInfoBox.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.tsx
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/components/TicketSearch/TicketSearch.scss
  src/components/TicketSearch/TicketSearchBox.tsx
  src/components/layout/Header/Header.scss
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/Logout.tsx
  src/hook/useCheckWindowWidth.ts
  src/styles/common.scss
  src/types/file.ts
  src/types/order.ts
  src/types/response.ts
  tsconfig.json
Labels: 개발

#159 🔀 merge: from feature/seat-map to dev
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seat-map.scss
  src/app/(primary)/order/seat-map/test/page.tsx
  src/app/(primary)/order/seat-map/test/seat-map-test.scss
Labels: 개발

#160 🔀 merge: from feature/payment to dev
  env.d.ts
  src/app/(primary)/order/complete/page.tsx
  src/auth.ts
Labels: 개발

#163 🔀 merge: from feature/payment to dev
  env.d.ts
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/layout.tsx
  src/data/actions/orderAction.ts
  src/lib/country.ts
  src/styles/globals.scss
  src/types/order.ts
  window.d.ts
Labels: 개발

#167 🔀 merge: from feature/seat-map to dev
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seat-map.scss
Labels: 개발, 디자인

#169 🔀 merge: from feature/e-ticket to dev
  src/app/e-ticket/[ticketId]/TicketPrint.tsx
  src/app/e-ticket/[ticketId]/[passengerId]/e-ticket.scss
  src/app/e-ticket/[ticketId]/[passengerId]/page.tsx
  src/app/e-ticket/[ticketId]/e-ticket.scss
  src/app/e-ticket/[ticketId]/page.tsx
Labels: 개발

#168 🔀 merge: from feature/reservation to dev
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/[reservationDetail]/Journery.scss
  src/app/(primary)/reservation/[reservationDetail]/Journey.tsx
  src/app/(primary)/reservation/[reservationDetail]/TicketLink.tsx
  src/app/(primary)/reservation/[reservationDetail]/page.tsx
  src/app/(primary)/reservation/[reservationDetail]/reservationDetail.scss
  src/app/(primary)/reservation/page.tsx
  src/app/(primary)/reservation/reservation.scss
Labels: 개발, 디자인

#170 🔀 merge: from feature/reservation to dev
  src/app/(primary)/reservation/OrdersItem.tsx
Labels: 개발

#171 🔀 merge: from feature/showAircraft to dev
  public/img/icon-craft.svg
  public/img/icon-warning-darkgray.svg
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/complete/[id]/TicketChk.tsx
  src/app/(primary)/order/complete/[id]/page.tsx
  src/app/(primary)/order/order.scss
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/atoms/atoms.ts
  src/data/actions/orderAction.ts
Labels: 개발

#172 🔀 merge: from feature/seatmap to dev
  public/img/icon-seat-exit.svg
  public/img/icon-seat-galley.svg
  public/img/icon-seat-toilet.svg
  public/img/icon-seat-wing.svg
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seat-map.scss
Labels: 개발, 디자인

#173 🔀 merge: from feature/ticketResult to dev
  api/dbinit/team/data.js
  public/img/icon-filter.svg
  public/img/icon-from-to.svg
  public/img/icon-no-result.svg
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.scss
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.scss
  src/app/(default)/(ticket)/ticket-result/TicketResultList.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/app/(default)/(ticket)/ticket-result/result.scss
  src/components/TicketSearch/SearchInfo.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/types/flight.ts
Labels: 개발

#181 🔀 merge: from feature/ticketResult to dev
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.scss
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.tsx
  src/app/(default)/(ticket)/ticket-result/result.scss
  src/hook/useCheckWindowWidth.ts
Labels: 개발

#183 🔀 merge: from feature/seatmap to dev
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seat-map.scss
Labels: 개발, 디자인

#184 🔀 merge: from feature/ticketPriceSearch to dev
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.scss
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.tsx
  src/app/(default)/(ticket)/ticket-result/error.tsx
  src/app/(default)/(ticket)/ticket-result/not-found.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/atoms/atoms.ts
  src/data/actions/flightPriceAction.ts
  src/data/fetch/fetchAuth.ts
  src/types/flight.ts
  src/types/order.ts
Labels: 개발

#186 🔀 merge: from feature/canvas to dev
  src/components/Ticket/Canvas.tsx
  src/components/Ticket/Ticket.tsx
  src/components/Ticket/ticket.scss
  src/styles/common.scss
Labels: 개발

#187 🔀 merge: from feature/seatmap to dev
  public/img/icon-seat-dog.svg
  public/img/icon-seat-select.svg
  public/img/icon-seat-selected.svg
  public/img/icon-seat-unselect.svg
  src/app/(primary)/order/seat-map/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seat-map.scss
  src/app/(primary)/order/seat-map/seatmapGrid.scss
  src/app/(primary)/order/seat-map/seatmapSelect.scss
  src/types/flight.ts
Labels: 개발, 디자인

#188 🔀 merge: from feature/orderDetailBug to dev
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/order.scss
  src/types/order.ts
Labels: 개발

#189 🔀 merge: from feature/seatmap to dev
  src/app/(primary)/order/seat-map/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/page.tsx
  src/app/(primary)/order/seat-map/seatmapGrid.scss
  src/app/(primary)/order/seat-map/seatmapSelect.scss
Labels: 개발, 디자인

#190 🔀 merge: from feature/ticketLoading to dev
  api/dbinit/team/data.js
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.scss
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.scss
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/atoms/atoms.ts
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.tsx
Labels: 개발

#191 🔀 merge: from eslintFix/heesun to dev
  src/app/e-ticket/[ticketId]/TicketPrint.tsx
  src/lib/seatMap.tsx
Labels: 개발

#192 🔀 merge: from feature/routeModalEdit to dev
  api/dbinit/team/data.js
Labels: 개발

#193 🔀 merge: from feature/seatmap to dev
  src/app/(default)/(ticket)/ticket-result/result.scss
  src/app/(default)/main.scss
  src/components/Banner/Banner.scss
  src/components/Modal/Modal.tsx
  src/styles/responsive.scss
Labels: 디자인

#194 🔀 merge: from EslintFix/SJ to dev
  .eslintrc.json
  auth.d.ts
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(transparent)/footprint/Animation.tsx
  src/app/(transparent)/footprint/page.tsx
  src/app/layout.tsx
  src/auth.ts
  src/components/Ticket/Ticket.tsx
  src/lib/countries.ts
Labels: 개발

#198 🔀 merge: from feature/seatmap to dev
  src/app/(primary)/order/seat-map/SeatmapGrid.tsx
  src/lib/seatMapa321.tsx
  src/lib/seatMapa380.tsx
  src/lib/seatMapb737.tsx
  src/lib/seatMapb747.tsx
  src/lib/seatMapb777.tsx
Labels: 개발

#199 🔀 merge: from feature/ticketFiltering to dev
  src/app/(default)/(ticket)/ticket-result/Filter.scss
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/app/(default)/(ticket)/ticket-result/result.scss
  src/components/Accordion/accordion.scss
  src/components/Modal/Modal.tsx
  src/components/layout/Header/Header.tsx
  src/styles/common.scss
Labels: 개발

#202 🔀 merge: from feature/ticketFiltering to dev
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
Labels: 개발

#203 🔀 merge: from feature/seatmap to dev
  src/app/(primary)/order/seat-map/seatmapGrid.scss
  src/app/(primary)/order/seat-map/seatmapSelect.scss
Labels: 디자인

#204 🔀 merge: from feature/seatmapGuide to dev
  src/app/(primary)/order/seat-map/seatmapSelect.scss
Labels: 디자인

#205 🔀 merge: from feature/seatmapWing to dev
  src/app/(primary)/order/seat-map/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/seatmapGrid.scss
Labels: 개발, 디자인

#206 🔀 merge: from feature/ticketSorting to dev
  api/dbinit/team/data.js
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/Sorting.tsx
  src/app/(default)/(ticket)/ticket-result/result.scss
  src/components/TicketSearch/SearchInfo.scss
Labels: 개발

#207 🔀 merge: from feature/ticketImgUpload to dev
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/order/payment/page.tsx
  src/app/(transparent)/footprint/page.tsx
  src/components/Ticket/Canvas.tsx
  src/components/Ticket/Ticket.tsx
  src/components/Ticket/ticket.scss
  src/data/actions/fileUploadAction.ts
  src/data/actions/orderAction.ts
  src/data/actions/orderPatchAction.ts
  src/types/order.ts
Labels: 개발

#208 🔀 merge: from feature/orderDetail to dev
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/Receipt.tsx
  src/atoms/atoms.ts
  src/hook/usePersonalPrice.ts
Labels: 개발

#209 🔀 merge: from feature/seatSelect to dev
  public/img/seat-selected.svg
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/app/(primary)/order/seat-map/[id]/seatmapGrid.scss
  src/app/(primary)/order/seat-map/[id]/seatmapSelect.scss
  src/app/(primary)/reservation/OrdersItem.tsx
  src/data/actions/seatSelect.ts
Labels: 개발, 디자인

#210 🔀 merge: from feature/ticketFilterUI to dev
  public/img/img-airplane-main.webp
  public/img/img-airplane-result.webp
  src/app/(default)/(ticket)/ticket-result/Filter.scss
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/Sorting.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultList.scss
  src/app/(default)/(ticket)/ticket-result/result.scss
  src/app/(default)/main.scss
  src/components/Modal/Modal.tsx
  src/components/layout/Header/Header.scss
Labels: 개발

#212 🔀 merge: from feature/noAlert to dev
  src/app/(primary)/notice/[id]/page.tsx
  src/app/(primary)/notice/page.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.tsx
  src/components/TicketSearch/SearchModals/ScheduleModal.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: QA

#213 🔀 merge: from feature/loading to dev
  public/lottie/loading.json
  src/app/loading.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/LoadingSpinner.tsx
Labels: 개발, 디자인

#214 🔀 merge: from feature/ticketLoading to dev
  src/app/(default)/(ticket)/ticket-result/Loading.scss
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
Labels: 개발

#215 🔀 merge: from feature/orderPost to dev
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/Order.tsx
  src/app/(primary)/order/OrderProgress.tsx
  src/app/(primary)/order/agree/page.tsx
  src/app/(primary)/order/complete/[id]/TicketChk.tsx
  src/app/(primary)/order/complete/[id]/page.tsx
  src/app/(primary)/order/layout.tsx
  src/app/(primary)/order/orderContext.ts
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/order/payment/page.tsx
  src/data/actions/orderAction.ts
Labels: 개발

#219 🔀 merge: from feature/ticketLoading to dev
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
Labels: 개발

#218 🔀 merge: from feature/seatmapLoading to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
Labels: 개발

#220 🔀 merge: from feature/loading to dev
  src/components/Loading/LoadingSpinner.tsx
Labels: 버그 수정

#221 🔀 merge: from feature/seatmapLoading to dev
  src/app/(primary)/order/seat-map/[id]/seatmapGrid.scss
  src/app/(primary)/order/seat-map/[id]/seatmapSelect.scss
Labels: 디자인

#222 🔀 merge: from feature/middleware to dev
  src/middleware.ts
Labels: 개발

#224 🔀 merge: from feature/ticketLoading to dev
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/app/(default)/(ticket)/ticket-result/TicketLoading.scss
  src/app/(default)/(ticket)/ticket-result/layout.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: SOS 구조요청

#225 🔀 merge: from feature/favicon to dev
  public/apple-touch-icon-16x16.ico
  public/apple-touch-icon-180x180.ico
  public/apple-touch-icon-32x32.ico
  public/apple-touch-icon-96x96.ico
  public/favicon-16x16.ico
  public/favicon-32x32.ico
  public/next.svg
  public/opengraph_img.svg
  public/vercel.svg
  src/app/layout.tsx
Labels: 개발

#226 🔀 merge: from feature/ticketResearch to dev
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/app/(default)/(ticket)/ticket-result/page.tsx
  src/components/TicketSearch/SearchInfo.tsx
  src/components/TicketSearch/SearchInfoBox.tsx
Labels: 개발

#227 Feature/seat select patch
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/app/(primary)/order/seat-map/[id]/seatmapSelect.scss
  src/data/actions/seatSelect.ts
Labels: 개발, 디자인

#228 🔀 merge: from feature/errorTicketResearch to dev
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/layout.tsx
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: SOS 구조요청

#230 🔀 merge: from feature/seatSelectModal to dev
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
Labels: 개발

#232 🔀 merge: from feature/seatselectModal to dev
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
Labels: 개발

#233 🔀 merge: from feature/seatPatch to dev
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/data/actions/seatSelectAction.ts
Labels: 개발

#234 🔀 merge: from feature/logout to dev
  package-lock.json
  package.json
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/SnsLogin.tsx
  src/app/(default)/(user)/login/page.tsx
  src/app/(transparent)/footprint/footprint.scss
  src/app/(transparent)/footprint/page.tsx
  src/auth.ts
  src/components/layout/Header/Logout.tsx
  src/data/actions/authAction.ts
  src/data/fetch/fetchAccessToken.ts
  src/types/response.ts
  src/types/user.ts
Labels: 개발

#235 🔖 release: ver 0.0.5
  package-lock.json
  package.json
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/app/(default)/(ticket)/ticket-result/TicketLoading.scss
  src/app/(default)/(ticket)/ticket-result/layout.tsx
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(default)/(user)/login/SnsLogin.tsx
  src/app/(default)/(user)/login/page.tsx
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/app/(transparent)/footprint/footprint.scss
  src/app/(transparent)/footprint/page.tsx
  src/app/loading.tsx
  src/auth.ts
  src/components/layout/Header/Logout.tsx
  src/data/actions/authAction.ts
  src/data/actions/seatSelectAction.ts
  src/data/fetch/fetchAccessToken.ts
  src/types/response.ts
  src/types/user.ts
Labels: 개발

#237 🔀 merge: from feature/loading to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/loading.tsx
  src/components/Loading/LoadingSpinner.tsx
Labels: 버그 수정, 개발

#239 🔀 merge: from feature/logout to dev
  src/components/layout/Header/Logout.tsx
Labels: 개발

#242 🔀 merge: from feature/orderQA to dev
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/app/(default)/(ticket)/ticket-result/TicketLoading.scss
  src/app/(primary)/order/Detail.tsx
  src/app/(primary)/order/Receipt.tsx
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/auth.ts
  src/components/Ticket/Ticket.tsx
  src/hook/usePersonalPrice.ts
  src/types/order.ts
Labels: 개발

#243 🔀 merge: from feature/ticketResultQA to dev
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/components/TicketSearch/SearchInfoBox.tsx
Labels: 개발

#245 🔀 merge: from feature/seatmapEdit to dev
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
Labels: 개발

#246 🔀 merge: from feature/QA to dev
  src/auth.ts
  src/components/Ticket/Ticket.tsx
  src/components/layout/Header/Logout.tsx
Labels: QA

#248 🔀 merge: from feature/ticketResultQA to dev
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#249 🔀 merge: from feature/seatmapGridDynamic to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/lib/seatMap-2-3-2.tsx
  src/lib/seatMap-2-3.tsx
  src/lib/seatMap-2-4-2.tsx
  src/lib/seatMap-3-3-3.tsx
  src/lib/seatMap-3-3.tsx
  src/lib/seatMap-3-4-3.tsx
  src/lib/seatmap.tsx
  src/types/code.ts
Labels: 개발

#250 🔀 merge: from feature/QA to dev
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/types/order.ts
Labels: QA

#251 🔀 merge: from feature/seatmapGridModal to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
Labels: 버그 수정, 개발

#252 🔖 release: ver 0.0.5
  src/app/(default)/(ticket)/ticket-result/Loading.tsx
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/components/TicketSearch/SearchModals/PassengersModal.scss
  src/components/TicketSearch/SearchModals/RouteModal.scss
  src/components/TicketSearch/SearchModals/ScheduleModal.scss
  src/components/TicketSearch/TicketSearchBox.tsx
  src/lib/seatMap-2-3-2.tsx
  src/lib/seatMap-2-3.tsx
  src/lib/seatMap-2-4-2.tsx
  src/lib/seatMap-3-3-3.tsx
  src/lib/seatMap-3-3.tsx
  src/lib/seatMap-3-4-3.tsx
  src/lib/seatmap.tsx
  src/types/code.ts
  src/types/order.ts
Labels: 개발

#253 🔀 merge: from feature/ticketQA to dev
  src/components/TicketSearch/SearchInfoBox.tsx
Labels: QA

#254 🔀 merge: from feature/seatmapQA to dev
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
Labels: 버그 수정, 개발

#255 🔀 merge: from feature/seatmapModalError to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
Labels: 버그 수정

#256 🔖 release: 좌석 선택 오류 수정
  src/app/(primary)/order/seat-map/[id]/CompleteButton.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGrid.tsx
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
  src/components/TicketSearch/SearchInfoBox.tsx
Labels: 개발

#257 🔀 merge: from feature/seatmapQA to dev
  src/app/(primary)/order/seat-map/[id]/SeatmapGroup.tsx
Labels: 개발

#261 🔀 merge: from feature/ticketSearchQA to dev
  README.md
  src/app/(default)/(ticket)/ticket-result/Result.tsx
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/loading.scss
  src/app/loading.tsx
  src/atoms/atoms.ts
  src/components/Modal/Modal.scss
  src/components/TicketSearch/TicketSearchBox.tsx
Labels: 개발

#260 🔀 merge: from feature/seatmapQA to dev
  src/app/(primary)/order/seat-map/[id]/page.tsx
Labels: 개발

#262 🔀 merge: from feature/QA to dev
  src/app/(primary)/reservation/[reservationDetail]/Journery.scss
  src/app/(primary)/reservation/[reservationDetail]/Journey.tsx
  src/app/(primary)/reservation/[reservationDetail]/page.tsx
  src/app/(primary)/reservation/[reservationDetail]/reservationDetail.scss
  src/app/(transparent)/footprint/page.tsx
  src/app/layout.tsx
Labels: QA

#264 🔀 merge: from feature/orderQA to dev
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/components/Ticket/Ticket.tsx
  src/styles/common.scss
Labels: QA

#265 🔀 merge: from feature/ticketSearchQA to dev
  README.md
  src/app/(default)/(ticket)/ticket-result/Filter.tsx
Labels: QA

#267 🔀 merge: from feature/reservationListQA to dev
  src/app/(primary)/reservation/OrdersItem.tsx
Labels: 개발

#268 🔀 merge: from feature/footerQA to dev
  src/components/layout/Footer/Footer.scss
  src/components/layout/Footer/Footer.tsx
Labels: 개발, 디자인

#271 🔀 merge: from feature/finalQA to dev
  README.md
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.scss
  src/app/(default)/(ticket)/ticket-result/error.scss
  src/app/(default)/(ticket)/ticket-result/error.tsx
  src/app/(default)/(ticket)/ticket-result/result.scss
Labels: 개발

#270 🔀 merge: from feature/Accessibility to dev
  src/app/(primary)/order/seat-map/[id]/page.tsx
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/(primary)/reservation/[reservationDetail]/Journey.tsx
  src/app/(primary)/reservation/[reservationDetail]/page.tsx
  src/app/(primary)/reservation/page.tsx
Labels: 개발

#273 🔀 merge: from docs to dev
  README.md
Labels: 문서화

#274 🔀 merge: from feature/formDataSetting to dev
  src/app/(primary)/order/payment/PaymentForm.tsx
Labels: 개발

#275 시연을 위한 임시 데이터 저장 후 배포
  README.md
  src/app/(primary)/order/payment/PaymentForm.tsx
Labels: 개발

#276 🔀 merge: from feature/formDataSetting to dev
  src/app/(primary)/order/payment/PaymentForm.tsx
Labels: 개발

#277 🔀 merge: from docs to dev
  README.md
Labels: 문서화
