Repository FRONTENDSCHOOLPLUS2/trifly, pull requests merged in 2025-01, with the labels that each got.

#381 Done: 테스트 안내 모달, 각 페이지 평가 모달
  public/img/icon-usertest-btn.svg
  src/app/(default)/(ticket)/ticket-result/TicketResultItem.tsx
  src/app/(primary)/order/payment/PaymentForm.tsx
  src/app/(primary)/reservation/OrdersItem.tsx
  src/app/layout.tsx
  src/atoms/atoms.ts
  src/components/Modal/Modal.scss
  src/components/Progress/Progress.tsx
  src/components/Progress/progress.scss
  src/components/Scroll/Scroll.scss
  src/components/Scroll/Scroll.tsx
  src/components/Ticket/Canvas.tsx
  src/components/Ticket/Ticket.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/UserTest/UserTest.scss
  src/components/layout/UserTest/UserTest.tsx
  src/components/layout/UserTest/UserTestMain.tsx
  src/components/layout/UserTest/UserTestPage.tsx
  src/data/actions/userTestAction.ts
  src/hook/useAddVisitedPage.ts
Labels: 개발, 디자인

#382 🔀 merge: from feature/userTest to dev
  public/img/icon-arrow-primary.svg
  public/img/icon-rating.svg
  src/app/(primary)/user-test/UserTestForm.tsx
  src/app/(primary)/user-test/page.tsx
  src/app/(primary)/user-test/user-test.scss
  src/components/layout/Header/Header.tsx
  src/components/layout/UserTest/UserTest.scss
  src/components/layout/UserTest/UserTestPage.tsx
  src/data/actions/userTestAction.ts
  src/styles/common.scss
Labels: 개발, 디자인

#384 Hotfix : 페이지네이션, 예약내역의 오류를 수정한다
  src/app/(primary)/reservation/(infiniteScroll)/OrdersList.tsx
  src/app/(primary)/reservation/Pagination.tsx
  src/app/(primary)/reservation/ReservationList.tsx
  src/app/(primary)/reservation/Search.tsx
  src/app/(primary)/reservation/[reservationDetail]/Journey.tsx
  src/lib/FetchOrderListScroll.tsx
Labels: 버그 수정, 리팩토링

#386 Done: 사용자 테스트 QA 반영
  src/app/(default)/(user)/login/LoginForm.tsx
  src/app/(primary)/user-test/UserTestForm.tsx
  src/components/layout/UserTest/UserTest.scss
Labels: 디자인, QA

#387 Done: 티켓 리펙토링 및 스타일 개선, 예약 진행 상태 스타일 개선
  src/app/(primary)/order/order.scss
  src/components/Ticket/Canvas.tsx
  src/components/Ticket/ticket.scss
Labels: 리팩토링, 디자인
